import Link from 'next/link';
import Image from 'next/image';
import { SiteHeader } from '@/components/site-header';
import { ThemeStyle } from '@/components/theme-style';
import { ThemeFX } from '@/components/theme-fx';
import { siteTheme } from '@/lib/site-theme';
import { LayoutTemplate, ArrowRight, Sparkles } from 'lucide-react';
import { getLocale } from '@/lib/i18n';
import { pagesDict } from '@/lib/pages-dict';
import { PRESETS, presetArtUrl } from '@/lib/presets';
import { presetDict } from '@/lib/preset-demo-dict';
import { getHeaderUser } from '@/lib/auth';

export async function generateMetadata() {
  const t = pagesDict(await getLocale()).presets;
  return { title: t.metaTitle, description: t.metaDesc };
}

/**
 * Static, pre-rendered cover image of the preset (generated by
 * scripts/preset-shots.mjs + optimized to .webp under public/media). Replaces
 * the old live-iframe preview, which loaded a full landing page per card and
 * made the index slow. Purely decorative — clicks fall through to the link.
 */
function LivePreview({ slug, title }: { slug: string; title: string }) {
  return (
    <div className="relative aspect-[16/10] overflow-hidden border-b border-border bg-muted">
      <Image
        src={presetArtUrl(`${slug}-cover`)}
        alt={title}
        aria-hidden
        fill
        loading="lazy"
        sizes="(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 33vw"
        className="select-none object-cover object-top"
      />
    </div>
  );
}

export default async function PresetsIndex() {
  const locale = await getLocale();
  const t = pagesDict(locale).presets;
  const d = presetDict(locale);
  const headerUser = await getHeaderUser();

  const presets = PRESETS.map((def) => {
    const c = d.presets[def.slug];
    return {
      slug: def.slug,
      href: `/presets/${def.slug}`,
      title: c.label,
      tag: c.tag,
      desc: c.hero.subtitle,
      sections: def.sections,
    };
  });

  return (
    <main className="min-h-dvh">
      <ThemeStyle theme={siteTheme()} />
      <ThemeFX />
      <SiteHeader initialUser={headerUser} />
      <div className="mx-auto max-w-[var(--container-max)] px-6 py-12 sm:px-10">
        <div className="mb-2 flex items-center gap-2">
          <LayoutTemplate className="h-6 w-6 text-primary" />
          <h1 className="font-display text-3xl font-black tracking-tight">{t.title}</h1>
        </div>
        <p className="mb-8 max-w-2xl text-muted-foreground">
          {t.intro}
        </p>

        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
          {presets.map((p) => (
            <Link key={p.slug} href={p.href} className="group">
              <div className="flex h-full flex-col overflow-hidden rounded-2xl border border-border bg-card/60 backdrop-blur transition-shadow hover:shadow-lg">
                <LivePreview slug={p.slug} title={t.previewOf.replace('{title}', p.title)} />
                <div className="flex flex-1 flex-col p-6">
                  <div className="mb-1 text-[11px] font-semibold uppercase tracking-widest text-primary">{p.tag}</div>
                  <div className="mb-3 flex items-center justify-between">
                    <h2 className="text-lg font-bold tracking-tight">{p.title}</h2>
                    <ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1" />
                  </div>
                  <p className="flex-1 text-sm text-muted-foreground">{p.desc}</p>
                  <div className="mt-4 flex flex-wrap gap-1.5">
                    {p.sections.map((s) => (
                      <span key={s} className="rounded-md bg-muted px-2 py-0.5 text-[11px] font-medium text-muted-foreground">
                        {s}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </div>

        <div className="mt-10 flex items-center gap-2 rounded-2xl border border-dashed p-6 text-sm text-muted-foreground">
          <Sparkles className="h-4 w-4 text-primary" />
          {t.customTitle}
        </div>
      </div>
    </main>
  );
}
