// Preset catalog: 6 ready-made, full-page landing compositions — one per
// industry, each rendered in its own theme for a distinct look. Purely a
// showcase/starting point: every control is a link (see PresetLanding), no
// forms or real logic. Text lives in lib/preset-demo-dict.ts (ru/en/hy); this
// file holds the non-localized design config (theme, icons, gradients, order).

export type PresetSection = 'stats' | 'logos' | 'features' | 'showcase' | 'gallery' | 'offer' | 'testimonials';

/** Real cinematic imagery per preset (generated by scripts/preset-art.mjs into
 *  public/media/generated/presets/<name>.webp). All fields optional so a preset
 *  can opt into only the sections it has art for; missing art falls back to the
 *  themed gradient so the page never breaks. */
export interface PresetArt {
  /** Framed hero image shown beside/under the hero copy. */
  hero?: string;
  /** Right-panel image inside the showcase block. */
  showcase?: string;
  /** Six tiles for the gallery grid. */
  gallery?: string[];
  /** Full-bleed background for the final CTA band. */
  cta?: string;
  /** Optional images layered on the three feature cards. */
  featureImages?: string[];
  /** Images for the "why us" rows (arena). */
  whyImages?: string[];
  /** Circular artist photos (pulse). */
  artistImages?: string[];
  /** Testimonial avatar images (index-matched to the testimonials array). */
  avatars?: string[];
}

export interface PresetDef {
  slug: string;
  /** Theme id applied to the whole page (unique palette / font / motion). */
  theme: string;
  /** Lucide icon keys (mapped in PresetLanding) for the three feature cards. */
  featureIcons: [string, string, string];
  /** Tailwind gradient for the index card cover + hero accent. */
  cover: string;
  /** Which optional sections render, in order (hero + final CTA are always on). */
  sections: PresetSection[];
  /** Style of the "offer" block: pricing tiers, a menu, or a schedule. */
  offerStyle: 'pricing' | 'menu' | 'schedule';
  /** Generated cinematic imagery wired into the sections. */
  art?: PresetArt;
}

/** Base path for all generated preset imagery. */
export const PRESET_ART_BASE = '/media/generated/presets';

/** Resolve an art base name to its public .webp URL. */
export function presetArtUrl(name: string): string {
  return `${PRESET_ART_BASE}/${name}.webp`;
}

export const PRESETS: PresetDef[] = [
  {
    slug: 'launch',
    theme: 'tech-saas',
    featureIcons: ['zap', 'shield', 'gauge'],
    cover: 'from-indigo-500 via-violet-500 to-sky-400',
    sections: ['logos', 'features', 'showcase', 'offer', 'testimonials'],
    offerStyle: 'pricing',
    art: {
      hero: 'launch-hero',
      showcase: 'launch-showcase',
      avatars: ['launch-av-1', 'launch-av-2'],
    },
  },
  {
    slug: 'roast',
    theme: 'editorial-coffee',
    featureIcons: ['coffee', 'leaf', 'heart'],
    cover: 'from-amber-700 via-orange-600 to-yellow-500',
    sections: ['showcase', 'gallery', 'offer', 'testimonials'],
    offerStyle: 'menu',
    art: {
      hero: 'roast-hero',
      gallery: ['roast-g1', 'roast-g2', 'roast-g3', 'roast-g4', 'roast-g5', 'roast-g6'],
      cta: 'roast-cta',
    },
  },
  {
    slug: 'arena',
    theme: 'sport-dynamic',
    featureIcons: ['dumbbell', 'flame', 'trophy'],
    cover: 'from-red-600 via-rose-500 to-orange-500',
    sections: ['stats', 'features', 'offer', 'testimonials'],
    offerStyle: 'schedule',
    art: {
      hero: 'arena-hero',
      featureImages: ['arena-f1', 'arena-f2', 'arena-f3'],
      whyImages: ['arena-why1', 'arena-why2', 'arena-why3'],
      cta: 'arena-cta',
      avatars: ['arena-av-1', 'arena-av-2'],
    },
  },
  {
    slug: 'studio',
    theme: 'modern-clean',
    featureIcons: ['pen-tool', 'layers', 'sparkles'],
    cover: 'from-blue-500 via-cyan-400 to-slate-300',
    sections: ['logos', 'gallery', 'showcase', 'testimonials'],
    offerStyle: 'pricing',
    art: {
      hero: 'studio-hero',
      showcase: 'studio-showcase',
      gallery: ['studio-g1', 'studio-g2', 'studio-g3', 'studio-g4', 'studio-g5', 'studio-g6'],
      cta: 'studio-cta',
    },
  },
  {
    slug: 'maison',
    theme: 'luxury-dark',
    featureIcons: ['gem', 'wine', 'star'],
    cover: 'from-yellow-600 via-amber-500 to-stone-700',
    sections: ['showcase', 'gallery', 'offer', 'testimonials'],
    offerStyle: 'menu',
    art: {
      hero: 'maison-hero',
      gallery: ['maison-g1', 'maison-g2', 'maison-g3', 'maison-g4', 'maison-g5', 'maison-g6'],
      cta: 'maison-cta',
    },
  },
  {
    slug: 'pulse',
    theme: 'neon-night',
    featureIcons: ['music', 'zap', 'ticket'],
    cover: 'from-fuchsia-500 via-purple-500 to-indigo-600',
    sections: ['stats', 'gallery', 'offer', 'testimonials'],
    offerStyle: 'schedule',
    art: {
      hero: 'pulse-hero',
      gallery: ['pulse-g1', 'pulse-g2', 'pulse-g3', 'pulse-g4', 'pulse-g5', 'pulse-g6'],
      cta: 'pulse-cta',
      artistImages: ['pulse-artist1', 'pulse-artist2', 'pulse-artist3', 'pulse-artist4', 'pulse-artist5'],
      avatars: ['pulse-artist1', 'pulse-artist2'],
    },
  },
];

export function getPreset(slug: string): PresetDef | undefined {
  return PRESETS.find((p) => p.slug === slug);
}
